version: '3'

services:
  postgres:
    image: postgres:10.0-alpine
    volumes:
      - ./backend/sql/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./backend/sql/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    environment:
      - POSTGRES_DB=docker
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
